-- 1. Create the table
create table leaderboard (
  id bigint generated by default as identity primary key,
  username text not null,
  score bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
alter table leaderboard enable row level security;

-- 3. Create Policy: Allow everyone to read scores
create policy "Enable read access for all users"
on leaderboard for select
using (true);

-- 4. Create Policy: Allow everyone to submit scores
create policy "Enable insert access for all users"
on leaderboard for insert
with check (true);
